- name: Run BuildBear CI
  uses: BuildBearLabs/buildbear_x_action@v1.0.0
  with:
    network: |
      [
        {
          "chainId": 1
        }
      ]
    deploy-command: docker compose -f docker-compose/docker-compose.yml up -d
    buildbear-api-key: ${{ secrets.BUILDBEAR_TOKEN }}